version: '3'

services:
   hw_user_api_fpm:
       image: php:7.2-alpine
       working_dir: /var/www
       command: php -S 0.0.0.0:8000 -t public
       ports:
           - 8000:8000
       volumes:
           - .:/var/www